# Generated by Django 5.0.6 on 2024-06-23 18:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name=())),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=512)),
                ('Email', models.EmailField(max_length=128)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='')),
                ('Description', models.CharField(blank=True, default='', max_length=1024)),
                ('Price', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('Image', models.ImageField(upload_to='upload/product')),
                ('Image1', models.ImageField(upload_to='upload/product')),
                ('Image2', models.ImageField(upload_to='upload/product')),
                ('Image3', models.ImageField(upload_to='upload/product')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lutos_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.DecimalField(decimal_places=0, default=0, max_digits=1200)),
                ('Address', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('Status', models.BooleanField(default=False, verbose_name='')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lutos_app.product', verbose_name='')),
            ],
        ),
    ]
