# Generated by Django 5.0.6 on 2024-07-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutos_app', '0005_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
