# Generated by Django 5.0.6 on 2024-07-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutos_app', '0006_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
